SHELL := /bin/sh

include ../config.mk

rust-examples:
	cd rust && make $@
	
c-examples: 
	cd c && make $@

dotnet-examples: 
	cd dotnet && make $@

java-examples:
	cd java && make $@

clean:
	cd rust && make $@
	cd c && make $@
	cd dotnet && make $@
	cd java && make $@